apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wireguard.fullname" . }}-config
data:
  wg0.conf: |
    [Interface]
    Address = {{ .Values.wireguard.config.address }}
    ListenPort = {{ .Values.wireguard.config.listenPort }}
    PostUp = wg set {{ .Values.wireguard.config.interfaceName }} private-key /etc/wireguard/privatekey && iptables -t nat -A POSTROUTING -s {{ .Values.wireguard.config.cidr }} -o eth0 -j MASQUERADE
    PostDown = iptables -t nat -D POSTROUTING -s {{ .Values.wireguard.config.cidr }} -o eth0 -j MASQUERADE
    SaveConfig = {{ .Values.wireguard.config.saveConfig }}
{{- range .Values.wireguard.peers }}

    [Peer]
    PublicKey = {{ .publicKey }}
    AllowedIPs = {{ .allowedIPs }}
{{- end }}