{{- $privateKey := .Values.wireguard.config.privateKey | required ".Values.wireguard.config.privateKey is required." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}-secret
type: Opaque
stringData:
  privatekey: "{{ $privateKey }}"
---
{{- if .Values.tunnel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}-tunnel-secret
type: Opaque
data:
  secret-key: {{ .Values.tunnel.secret | default (randAlphaNum 42 | b64enc ) }}
{{- end }}