name: Publish images

on:
  push:
    branches:
      - main

jobs:
  discover-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find-changes.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find changed projects with Dockerfiles
        id: find-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          echo "Files changed in this push:"
          echo "$CHANGED_FILES"
          echo "-------------------------------------------"
          PROJECTS_TO_BUILD=()
          for dir in */; do
            dir_name=${dir%/}
            if [ -f "${dir_name}/Dockerfile" ]; then
              echo "Project '$dir_name' contains a Dockerfile. Checking for changes..."
              if echo "$CHANGED_FILES" | grep -q "^${dir_name}/"; then
                echo "-> Changes detected in '$dir_name'. Adding to build matrix."
                PROJECTS_TO_BUILD+=("\"${dir_name}\"")
              else
                echo "-> No changes detected in '$dir_name'."
              fi
            fi
          done
          MATRIX="[$(IFS=,; echo "${PROJECTS_TO_BUILD[*]}")]"
          echo "-------------------------------------------"
          echo "Final build matrix: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover-changes
    if: ${{ needs.discover-changes.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.discover-changes.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable=true
      - name: Build and push Docker image for ${{ matrix.project }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.project }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}